backend:
  name: github
  repo: CaroDersoir/voix_lactee
  branch: main

locale: fr
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: songs
    label: Chants
    folder: src/content/songs
    create: true
    delete: true
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { label: Titre, name: title, widget: string }
      - { label: Tonalité, name: key, widget: string, required: false }
      - label: Type de chant
        name: occasion
        widget: select
        required: false
        options:
          - Accueil
          - Kyrie
          - Gloria
          - Psaume
          - Alléluia
          - Prière universelle
          - Offertoire
          - Sanctus
          - Agnus Dei
          - Communion
          - Action de grâce
          - Envoi
          - En plus
          - Autre
      - { label: Partition PDF, name: pdf, widget: file, required: false }
      - { label: Notes, name: body, widget: markdown, required: false }

  - name: events
    label: Agenda
    folder: src/content/events
    create: true
    delete: true
    identifier_field: title
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Titre, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: Heure, name: time, widget: string, hint: "Ex. : 10:30" }
      - { label: Lieu, name: location, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Détails, name: body, widget: markdown, required: false }
